package whimsy

// plants contains 200+ plant names, all lowercase a-z, max 6 characters, alphabetically ordered
var plants = []string{
	"acacia", "acer", "acorn", "agave", "alder", "algae", "almond", "aloe", "amber",
	"apple", "arbor", "arnica", "ash", "aspen", "aster", "azalea", "bamboo",
	"bark", "barley", "basil", "bay", "bean", "beech", "beet", "berry", "birch",
	"blade", "bloom", "bonsai", "bough", "bower", "brake", "branch", "briar",
	"broom", "brush", "bud", "bulb", "bush", "cacao", "cactus", "cane", "carrot",
	"cedar", "cherry", "chive", "cholla", "clover", "cocoa", "cone", "corn", "cosmos",
	"cotton", "cress", "crocus", "cumin", "cycad", "dahlia", "daisy", "date",
	"dingle", "dock", "dune", "elm", "fennel", "fern", "fescue", "fiber", "ficus",
	"fig", "fir", "flax", "flora", "fruit", "fungus", "garlic", "ginger", "glade",
	"gourd", "grain", "grape", "grass", "grove", "hazel", "heath", "hemp", "herb",
	"holly", "hop", "hosta", "husk", "iris", "ivy", "kale", "knoll", "knot", "lance",
	"larch", "laurel", "lea", "leaf", "lemon", "lichen", "lilac", "lily", "lime",
	"lotus", "lupine", "mango", "maple", "marsh", "meadow", "melon", "mint",
	"moor", "moss", "myrtle", "nettle", "nut", "oak", "oat", "olive", "onion", "orchid",
	"palm", "pansy", "papaya", "patch", "peach", "pear", "peas", "pecan", "peony",
	"pepper", "petal", "phlox", "pine", "pod", "poplar", "poppy", "potato", "privet",
	"radish", "rattan", "reed", "rice", "ridge", "root", "rose", "rowan", "rush", "rye",
	"sap", "scrub", "sedge", "seed", "senna", "shade", "shrub", "spike", "spore",
	"sprig", "sprout", "spruce", "squash", "stalk", "stand", "stem", "sumac", "swale",
	"sward", "switch", "tangle", "tassel", "thatch", "thick", "thorn", "thyme", "tree",
	"trunk", "tulip", "turf", "turnip", "twig", "twine", "umbel", "vale", "vetch",
	"vine", "violet", "walnut", "weald", "wheat", "willow", "wood", "yam", "yarrow",
	"yew", "yucca", "zinnia",
}

// animals contains 200+ animal names, all lowercase a-z, max 6 characters, alphabetically ordered
var animals = []string{
	"adder", "akita", "alpaca", "ant", "ape", "asp", "badger", "bass", "bat", "beagle",
	"bear", "beaver", "bee", "beetle", "betta", "bird", "bison", "boa", "boar", "bobcat",
	"boxer", "bream", "budgie", "bug", "bull", "bunny", "burro", "camel", "canary",
	"canine", "carp", "cat", "cattle", "chick", "chimp", "chow", "cicada", "clam", "cod",
	"collie", "condor", "corgi", "cow", "coyote", "coypu", "crab", "crane", "crow",
	"cub", "deer", "dingo", "dodo", "doe", "dog", "donkey", "dove", "drake", "drone",
	"duck", "eagle", "eel", "elk", "emu", "ermine", "ewe", "falcon", "fawn", "ferret",
	"finch", "fish", "flea", "fly", "foal", "fowl", "fox", "frog", "gecko", "gibbon",
	"gnat", "goat", "goose", "gopher", "grebe", "grouse", "guinea", "gull", "guppy",
	"hake", "hare", "hawk", "hen", "heron", "hippo", "horse", "hound", "husky", "hyena",
	"ibis", "iguana", "jackal", "jaguar", "jay", "joey", "kitten", "koala", "lamb",
	"lark", "lemur", "liger", "lion", "lizard", "llama", "louse", "lynx", "magpie",
	"mantis", "marten", "midge", "mink", "minnow", "mole", "monkey", "moose", "moth",
	"mouse", "newt", "ocelot", "orca", "oriole", "osprey", "otter", "owl", "ox",
	"oyster", "panda", "parrot", "pekin", "perch", "pig", "pigeon", "pike", "pony",
	"poodle", "possum", "puma", "puppy", "python", "quail", "quokka", "rabbit", "ram",
	"rat", "raven", "rhino", "roach", "robin", "salmon", "seal", "setter", "shark",
	"sheep", "shiba", "shrimp", "skate", "skunk", "sloth", "snail", "snake", "sole",
	"sow", "spider", "squid", "stag", "stoat", "stork", "swan", "tabby", "thrush",
	"tick", "tiger", "toad", "toucan", "trout", "tuna", "turkey", "turtle", "viper",
	"vizsla", "walrus", "wasp", "weasel", "weevil", "whale", "wolf", "wombat", "worm",
	"yak", "yeti", "zebra", "zebu",
}

// colors contains 200+ color names, all lowercase a-z, max 6 characters, alphabetically ordered
var colors = []string{
	"acid", "alice", "almond", "amber", "aqua", "arctic", "army", "ash", "autumn",
	"azure", "banana", "basic", "beach", "beige", "bisque", "bistre", "black", "blanc",
	"blaze", "blond", "blue", "blush", "bone", "brass", "brick", "bright", "bronze",
	"brown", "buff", "burnt", "butter", "cadet", "camel", "cameo", "candy", "carbon",
	"cedar", "cement", "cerise", "char", "cherry", "china", "choco", "chrome", "citron",
	"citrus", "claret", "clay", "coffee", "copper", "coral", "cosmic", "cotton", "cream",
	"cyan", "dark", "dawn", "deep", "denim", "desert", "dim", "dirt", "dove", "duck",
	"dull", "dusk", "earth", "ebony", "elder", "ember", "faded", "fair", "fawn", "felt",
	"field", "fire", "flame", "flax", "flirt", "fog", "forest", "fresh", "frost",
	"garnet", "ghost", "gleam", "gloss", "glow", "gold", "green", "grey", "haze",
	"honey", "ice", "indigo", "iron", "ivory", "jade", "jet", "khaki", "kobi", "lace",
	"laser", "lava", "light", "lilac", "lime", "linen", "lunar", "mango", "maroon",
	"mauve", "medium", "metal", "milk", "mist", "mocha", "moss", "muted", "navy", "neon",
	"ocean", "ochre", "olive", "onyx", "opal", "orange", "orchid", "oxford", "pale",
	"papaya", "pastel", "pearl", "peru", "pink", "plum", "pomelo", "powder", "prune",
	"puce", "purple", "quartz", "raisin", "red", "rich", "rose", "royal", "ruby", "rust",
	"rustic", "sage", "sand", "sandy", "seal", "sepia", "shade", "sheen", "shine",
	"sienna", "silk", "silver", "sky", "slate", "smalt", "smoke", "snow", "soft",
	"solar", "space", "spark", "steel", "stone", "storm", "straw", "suede", "sunny",
	"sunset", "sweet", "tan", "taupe", "tea", "teal", "tint", "tomato", "tone", "umber",
	"vivid", "warm", "water", "wave", "wheat", "white", "wine", "wood", "wool",
	"yankee", "yellow", "zaffre", "zest", "zinc",
}
