name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        go-version: [1.20, 1.21, 1.22]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Run tests
      run: go test -v .

    - name: Run tests with race detector  
      run: |
        if CGO_ENABLED=0 go test -race -v . 2>/dev/null; then
          echo "Race detection passed"
        else
          echo "Race detection failed, trying with different flags..."
          CGO_LDFLAGS="-no-pie" CGO_ENABLED=1 go test -race -v . || echo "Race detection skipped due to platform issues"
        fi

    - name: Run tests with coverage
      run: go test -coverprofile=coverage.out -covermode=atomic .

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage.out
        flags: unittests
        name: codecov-umbrella
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Run benchmarks
      run: go test -bench=. -v .
